SGMII core: resolve problems with packet transmission
clash-lang/clash-cores pull request #22
Opened 2024-12-07 14:29 UTC by jvnknvlgl

This is a draft PR to resolve problems with packet transmission of the SGMII core. I will use this to track progress and mark observations.

Current actions:

- Discovered problem with packet transmission on hardware: some octets of the preamble are missing, and two extra empty (zero) octets are added before the `/T/` and `/R/` sequence indicating the end of a packet.
- Reproduced the issue in simulation: with the same input on `TXD` as in hardware, the issue can be reproduced in simulation.

Observations:

- While normally the preamble of an ethernet packet should be 7 times `0x55`, the intended output of the PCS transmit should only contain 6 times `0x55` as the start-of-packet code group `/S/` is replaced with `0x55` at the PCS receive.
- If `TX_EN` is asserted while the PCS receive code group process is in `IDLE_DISPARITY_WRONG` or `IDLE_DISPARITY_OK`, another octet of the preamble is missing as the system still needs to move through `IDLE_IB`.

Possible solution: add a queue for values coming from `TXD` that gets emptied when `TX_OSET.indicate` is issued, regardless of what the value of `TX_EN` is? This is thought-in-process.

2025-01-26 16:30 UTC, DigitalBrains1 commented
I just manually made CI run, in basically the same manner that we use kloonbot on `clash-compiler`, except just by hand without a bot. I thought it might be useful to you.

2025-03-01 17:46 UTC, jvnknvlgl commented
Some updates: a new block was added that fixes the initial part of a packet, but there are still issues with the termination of a packet. Currently the third-to-last input value might get duplicated.

2025-03-01 20:55 UTC, jvnknvlgl commented
This seems to be done now (finally!), but I would like to test it on hardware once more to be completely certain. Other than that, it is ready for review :)

2025-04-10 12:43 UTC, jvnknvlgl commented
```
PING 10.0.0.2 (10.0.0.2) 56(84) bytes of data.
 
--- 10.0.0.2 ping statistics ---
100000 packets transmitted, 100000 received, 0% packet loss, time 25283ms
rtt min/avg/max/mdev = 0.229/0.236/0.949/0.007 ms, ipg/ewma 0.252/0.237 ms
```

Ethernet goes brrr

2025-04-10 13:37 UTC, DigitalBrains1 commented
I am not familiar with the code (other than that bit about the hardcoded tables of code points that I spent some time on back when).

(BTW, I just fired up CI. We still need a bot for this, it's still manual.)

2025-04-16 06:28 UTC, lmbollen commented
I won't have time until next week at the earliest

2025-04-30 11:39 UTC, lmbollen requested changes
Thanks for your work :) Could you look at the requested changes and re-review them?

If you don't wish to spend more time on it, I'm willing to take over the PR, just let me know.

2025-04-30 11:39 UTC, lmbollen commented on src/Clash/Cores/Sgmii/PcsTransmit.hs
> +    | not (txEn || txEr) && cur' < minBound + 2 = f (txs' !! cur')
Can you elaborate on the constant 2?

2025-04-30 11:39 UTC, lmbollen commented on src/Clash/Cores/Sgmii/PcsTransmit.hs
> +      (0, replicate d5 (False, False, 0))
Why do you need a size of 5 elements?

2025-04-30 11:39 UTC, lmbollen commented on src/Clash/Cores/Sgmii/PcsTransmit.hs
> +--   earlier than when it goes up.
Could you shortly mention the justification that the statemachine has states where it can not consume the input, but the GMII protocol does not feature a backpressure mechanism.

2025-04-30 14:40 UTC, jvnknvlgl commented on src/Clash/Cores/Sgmii/PcsTransmit.hs
> +    | not (txEn || txEr) && cur' < minBound + 2 = f (txs' !! cur')
Yeah, I'm not entirely sure anymore (I should have documented this...) but I think my intention here is to make sure the `OrderedSet` state machine is in the right position such that it sends out the correct end-of-packet symbols. I will check this.

2025-04-30 14:42 UTC, jvnknvlgl commented on src/Clash/Cores/Sgmii/PcsTransmit.hs
> +      (0, replicate d5 (False, False, 0))
I experimentally determined that 5 is the correct amount (so, basically by decreasing the amount of elements until unit tests started failing). This can be verified by counting the required amount of cycles / transitions before the system is able to ingest any incoming data.

2025-05-06 13:45 UTC, lmbollen commented on src/Clash/Cores/Sgmii/PcsTransmit.hs
> +      (0, replicate d5 (False, False, 0))
Alright

2025-05-08 10:50 UTC, lmbollen approved these changes
Feel free to squash + merge!

2025-05-08 11:47 UTC, jvnknvlgl commented
Unfortunately I do not have permission, but other than that, very nice!

2025-05-08 12:06 UTC, merged